import type { ThreatScenario } from "./types";

export const threatLabScenarios: ThreatScenario[] = [
  {
    id: "email-phishing-payroll",
    title: "Payroll Reset Phishing",
    typeLabel: "Email phishing",
    summary:
      "A spoofed payroll warning pressures the user to reset credentials before salaries are delayed.",
    brief:
      "Inspect the email like a real operator. Flag every suspicious element before submitting your assessment.",
    difficulty: "Moderate",
    threatScore: 91,
    focus: "Spoofing, urgency, credential theft",
    objective: "Spot the sender manipulation, urgent coercion, and credential-harvesting path.",
    analystIntro: "AI analyst watching for domain spoofing, urgency cues, and credential collection patterns.",
    aiExplanation:
      "This scenario blends payroll anxiety with domain impersonation. The attacker wants the victim to react before verifying the sender, then route them through a credential capture page and OTP follow-up.",
    outcome:
      "Strong performers pause the workflow, verify the sender through official HR channels, and avoid clicking the reset link.",
    mitigation: [
      "Verify payroll or HR messages through the official portal rather than embedded links.",
      "Compare sender and reply-to domains before acting on reset instructions.",
      "Report suspicious payroll communications so similar lures can be blocked for the wider team.",
    ],
    surface: {
      type: "email",
      atmosphere: "Inbox simulation",
      guidance: "Click suspicious elements directly inside the message to flag them.",
      sender: "Payroll Security <payroll@company-payrolI.com>",
      replyTo: "helpdesk@secure-reset-now.co",
      subject: "Immediate payroll reset required before 4:00 PM",
      preview: "We detected a payroll sync failure. Confirm your credentials to avoid salary delays.",
      timestamp: "Today, 3:14 PM",
      body: [
        "We noticed unusual payroll activity tied to your employee profile.",
        "To prevent direct deposit delays, you must reconfirm your password and MFA code before 4:00 PM.",
        "If you do not comply, payroll processing may be suspended for this cycle.",
      ],
      ctaLabel: "Re-secure payroll access",
      attachment: "Updated_Payroll_Policy.html",
    },
    targets: [
      {
        id: "email-sender",
        label: "Spoofed sender",
        description: "The sender domain uses a capital I to mimic a legitimate payroll address.",
        suspicious: true,
        severity: "high",
        points: 26,
      },
      {
        id: "email-reply-to",
        label: "Mismatch reply-to",
        description: "Replies redirect to an unrelated reset domain controlled by the attacker.",
        suspicious: true,
        severity: "high",
        points: 22,
      },
      {
        id: "email-urgency",
        label: "Urgency language",
        description: "The message creates panic with salary-delay pressure and a near-term deadline.",
        suspicious: true,
        severity: "medium",
        points: 16,
      },
      {
        id: "email-cta",
        label: "Credential harvesting link",
        description: "The reset CTA is the attacker’s main path to capture passwords and MFA codes.",
        suspicious: true,
        severity: "high",
        points: 24,
      },
      {
        id: "email-attachment",
        label: "Unexpected attachment",
        description: "A policy attachment in HTML format can deliver a fake login flow or script.",
        suspicious: true,
        severity: "medium",
        points: 12,
      },
      {
        id: "email-timestamp",
        label: "Internal timestamp",
        description: "A same-day timestamp alone is not malicious.",
        suspicious: false,
        severity: "low",
        points: 6,
      },
    ],
  },
  {
    id: "fake-bank-login",
    title: "Bank Session Verification",
    typeLabel: "Fake login form",
    summary:
      "A cloned banking page claims the user must verify a flagged device immediately to keep transfers enabled.",
    brief:
      "Treat the page as a live phishing site. Flag the elements that prove it is hostile or unsafe.",
    difficulty: "High",
    threatScore: 95,
    focus: "URL spoofing, fear prompts, data capture",
    objective: "Identify the spoofed URL, excessive data request, and coercive warning copy.",
    analystIntro: "AI analyst correlating cloned brand assets with phishing-kit indicators.",
    aiExplanation:
      "The attacker copied the visual language of a real bank while using a deceptive URL and abnormal form requirements. The goal is to normalize full credential entry plus secondary account information under pressure.",
    outcome:
      "Effective defenders look past brand visuals, validate the domain, and recognize that banks do not request full recovery details from unsolicited security prompts.",
    mitigation: [
      "Always navigate to banking services through a trusted bookmark or official app.",
      "Treat account warnings that demand immediate login outside normal channels as suspect.",
      "Escalate spoofed banking pages so takedown and block-list actions can begin quickly.",
    ],
    surface: {
      type: "login",
      atmosphere: "Cloned login page",
      guidance: "Inspect the URL, prompts, and form requests before trusting the page.",
      brand: "First National Secure",
      url: "https://firstnational-verify-secure-login.com/session/restore",
      title: "Session verification required",
      subtitle: "Your transfer privileges will be paused unless you restore access now.",
      alerts: [
        "Device anomaly detected in Mumbai at 14:02.",
        "Re-enter your account password and backup phrase to maintain wire access.",
      ],
      fields: ["Customer ID", "Password", "Backup phrase", "Card PIN"],
      ctaLabel: "Restore secure session",
      footer: "Protected by enterprise anti-fraud gateway.",
    },
    targets: [
      {
        id: "login-url",
        label: "Spoofed domain",
        description: "The URL contains extra trust words and does not match the real bank domain.",
        suspicious: true,
        severity: "high",
        points: 28,
      },
      {
        id: "login-subtitle",
        label: "Threatening account warning",
        description: "The copy pressures the user with immediate loss of service.",
        suspicious: true,
        severity: "medium",
        points: 16,
      },
      {
        id: "login-fields",
        label: "Over-collection of secrets",
        description: "The form requests backup phrase and card PIN, which is abnormal and dangerous.",
        suspicious: true,
        severity: "high",
        points: 30,
      },
      {
        id: "login-alerts",
        label: "Fear-based anomaly script",
        description: "The alert wording is designed to rush the victim into bypassing scrutiny.",
        suspicious: true,
        severity: "medium",
        points: 14,
      },
      {
        id: "login-cta",
        label: "Fraud submission button",
        description: "Submitting here sends sensitive data directly to the phishing kit.",
        suspicious: true,
        severity: "high",
        points: 12,
      },
      {
        id: "login-brand",
        label: "Bank logo treatment",
        description: "Branding presence alone is not proof of compromise.",
        suspicious: false,
        severity: "low",
        points: 6,
      },
    ],
  },
  {
    id: "sms-support-scam",
    title: "Delivery Support SMS Hijack",
    typeLabel: "SMS scam",
    summary:
      "A text thread impersonates courier support and steers the user into a payment and credential recovery flow.",
    brief:
      "Review the conversation like a mobile user. Tap suspicious bubbles and actions before you submit.",
    difficulty: "Moderate",
    threatScore: 84,
    focus: "Smishing, payment bait, fake support",
    objective: "Detect the spoofed support path, short-link trap, and verification request.",
    analystIntro: "AI analyst monitoring smishing language patterns and fake support escalation cues.",
    aiExplanation:
      "This is a classic support pretext: the attacker creates a minor delivery issue, then introduces a fake fee and a link to capture card details or account credentials.",
    outcome:
      "High performers verify courier issues in the official app, distrust unsolicited short links, and avoid sharing verification codes over text.",
    mitigation: [
      "Open delivery issues from the courier’s official app or website, not a text message.",
      "Never send one-time codes or account confirmations to support contacts from SMS.",
      "Block and report smishing numbers so mobile filtering can improve over time.",
    ],
    surface: {
      type: "sms",
      atmosphere: "Mobile message simulation",
      guidance: "Tap the suspicious messages or action pill to flag them.",
      contact: "ExpressParcel Support",
      number: "+44 7700 900146",
      messages: [
        { id: "sms-1", from: "them", text: "Your parcel is on hold because of an address validation fee." },
        { id: "sms-2", from: "them", text: "Pay Rs 29 here now: https://exp-resolve-delivery.help/track" },
        { id: "sms-3", from: "you", text: "I already paid shipping. Why another fee?" },
        { id: "sms-4", from: "them", text: "Complete it in 10 minutes or the package will be returned." },
        { id: "sms-5", from: "them", text: "Reply with the OTP after checkout so support can finalize release." },
      ],
      quickAction: "Open payment link",
    },
    targets: [
      {
        id: "sms-number",
        label: "Untrusted support number",
        description: "The message comes from an unknown number rather than a verified courier shortcode.",
        suspicious: true,
        severity: "medium",
        points: 16,
      },
      {
        id: "sms-link",
        label: "Payment short-link",
        description: "The delivery-help domain is not an official courier property.",
        suspicious: true,
        severity: "high",
        points: 28,
      },
      {
        id: "sms-urgency",
        label: "Return deadline pressure",
        description: "The 10-minute timer is a coercive tactic meant to reduce careful checking.",
        suspicious: true,
        severity: "medium",
        points: 14,
      },
      {
        id: "sms-otp",
        label: "OTP harvesting request",
        description: "Legitimate support should never request an OTP over chat to finish delivery.",
        suspicious: true,
        severity: "high",
        points: 28,
      },
      {
        id: "sms-action",
        label: "External payment action",
        description: "The quick action launches the attacker’s payment collection path.",
        suspicious: true,
        severity: "medium",
        points: 10,
      },
      {
        id: "sms-user-reply",
        label: "Victim clarification",
        description: "Your own reply bubble is not a threat indicator.",
        suspicious: false,
        severity: "low",
        points: 6,
      },
    ],
  },
  {
    id: "crypto-wallet-drain",
    title: "Wallet Reconnect Drain",
    typeLabel: "Crypto wallet scam",
    summary:
      "A wallet panel claims an airdrop requires reconnection, signature approval, and emergency seed confirmation.",
    brief:
      "Audit the wallet request carefully. Flag the prompts that indicate a drain or credential theft attempt.",
    difficulty: "High",
    threatScore: 97,
    focus: "Wallet drain, seed theft, fake urgency",
    objective: "Catch the malicious destination, fake countdown, and secret recovery request.",
    analystIntro: "AI analyst comparing wallet prompts against known drain-kit behavior.",
    aiExplanation:
      "The simulation chains multiple crypto scam tactics together: a reward incentive, an urgent countdown, and a seed phrase prompt. Any one of those should halt the interaction immediately.",
    outcome:
      "Defenders reject wallet prompts that request recovery phrases, verify destination addresses independently, and distrust countdown-driven reconnect flows.",
    mitigation: [
      "Never enter or transmit a wallet seed phrase into reconnect or claim flows.",
      "Validate dApp permissions and destination addresses in a trusted wallet interface.",
      "Use hardware wallet confirmation screens to inspect what is actually being signed.",
    ],
    surface: {
      type: "wallet",
      atmosphere: "Wallet connect simulation",
      guidance: "Review the wallet request as if you are protecting real funds.",
      appName: "Nebula Rewards Portal",
      walletId: "0x4a6B...91eC",
      network: "Ethereum Mainnet",
      amount: "2.48 ETH approval",
      destination: "0xDEAD9f1cA44...fE02",
      messages: [
        "Reconnect wallet to unlock your pending governance airdrop.",
        "Security sync expires in 02:17.",
        "Enter your 12-word recovery phrase if auto-verification fails.",
      ],
      ctaLabel: "Approve reconnect",
    },
    targets: [
      {
        id: "wallet-destination",
        label: "Unknown destination",
        description: "The approval points to an unfamiliar address that could drain wallet permissions.",
        suspicious: true,
        severity: "high",
        points: 24,
      },
      {
        id: "wallet-countdown",
        label: "Countdown coercion",
        description: "The short timer is meant to force approval before verification.",
        suspicious: true,
        severity: "medium",
        points: 14,
      },
      {
        id: "wallet-seed",
        label: "Seed phrase request",
        description: "Any request for the wallet recovery phrase is an immediate red flag.",
        suspicious: true,
        severity: "high",
        points: 32,
      },
      {
        id: "wallet-amount",
        label: "Large approval amount",
        description: "The amount and approval language do not match a simple reward claim.",
        suspicious: true,
        severity: "high",
        points: 18,
      },
      {
        id: "wallet-cta",
        label: "Reconnect approval button",
        description: "The CTA advances the scam and conditions the victim to approve blindly.",
        suspicious: true,
        severity: "medium",
        points: 10,
      },
      {
        id: "wallet-network",
        label: "Network label",
        description: "The network label itself is expected and not malicious.",
        suspicious: false,
        severity: "low",
        points: 6,
      },
    ],
  },
  {
    id: "invoice-malware",
    title: "Vendor Invoice Malware",
    typeLabel: "Invoice malware",
    summary:
      "An accounts-payable email delivers a document that claims to include overdue invoice details and macros for secure viewing.",
    brief:
      "Investigate the invoice workflow, then flag the clues that indicate malware delivery or financial fraud.",
    difficulty: "Moderate",
    threatScore: 88,
    focus: "Malicious attachment, vendor impersonation, macro lure",
    objective: "Identify the fake sender, dangerous attachment path, and payment-update manipulation.",
    analystIntro: "AI analyst reviewing finance-targeted attachment delivery patterns.",
    aiExplanation:
      "This scenario combines malware distribution with vendor impersonation. The attachment is the initial payload, and the banking update language can also redirect future payments if the victim trusts the sender.",
    outcome:
      "Good responders verify with the vendor out of band, avoid enabling content in documents, and isolate suspicious attachments for analysis.",
    mitigation: [
      "Confirm invoice changes with the vendor using an existing trusted contact method.",
      "Never enable macros or editing in unsolicited invoice documents.",
      "Submit suspicious financial attachments for sandbox analysis before opening them.",
    ],
    surface: {
      type: "invoice",
      atmosphere: "Accounts payable simulation",
      guidance: "Click the risky parts of the invoice email and attachment prompt.",
      sender: "Apex Supplies Billing <billing@apex-supplles.com>",
      subject: "Outstanding invoice INV-88421 - payment update attached",
      company: "Apex Supplies Ltd.",
      invoiceId: "INV-88421",
      body: [
        "Please review the attached invoice before today’s reconciliation close.",
        "Our banking details changed this morning, so use the updated account listed in the sheet.",
        "If the document opens in protected mode, enable content to display secure line items.",
      ],
      attachment: "Invoice_INV-88421.xlsm",
      ctaLabel: "Open invoice attachment",
    },
    targets: [
      {
        id: "invoice-sender",
        label: "Vendor impersonation domain",
        description: "The sender domain misspells the legitimate vendor name.",
        suspicious: true,
        severity: "high",
        points: 24,
      },
      {
        id: "invoice-bank-update",
        label: "Unexpected banking change",
        description: "A sudden banking update in email is a common fraud tactic.",
        suspicious: true,
        severity: "medium",
        points: 18,
      },
      {
        id: "invoice-macro",
        label: "Enable content lure",
        description: "The email explicitly asks the user to enable content in a macro-enabled spreadsheet.",
        suspicious: true,
        severity: "high",
        points: 28,
      },
      {
        id: "invoice-attachment",
        label: "Macro-enabled attachment",
        description: "An unsolicited `.xlsm` invoice is a high-risk malware delivery vehicle.",
        suspicious: true,
        severity: "high",
        points: 20,
      },
      {
        id: "invoice-cta",
        label: "Attachment open action",
        description: "The CTA drives execution of the malicious document.",
        suspicious: true,
        severity: "medium",
        points: 10,
      },
      {
        id: "invoice-id",
        label: "Invoice reference number",
        description: "An invoice ID alone is not suspicious.",
        suspicious: false,
        severity: "low",
        points: 6,
      },
    ],
  },
];
